### ISSUE TITLE
LighthouseError: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by Kingwl** [perfsee/perfsee#336]
[Worker] - 2023-03-03T03:03:19.339Z  VERBOSE Gathering trace
[Worker] - 2023-03-03T03:03:19.418Z  VERBOSE Gathering devtoolsLog & network records
[Worker] - 2023-03-03T03:03:49.423Z  VERBOSE Disconnecting from browser...
[Worker] - 2023-03-03T03:03:49.423Z  VERBOSE Cleaning origin data
[Worker] - 2023-03-03T03:03:49.425Z    ERROR Lab Round #1 failed {
  error: LighthouseError [LHError]: PROTOCOL_TIMEOUT
      at /code/node_modules/lighthouse/lighthouse-core/gather/driver.js:348:50
      at new Promise (<anonymous>)
      at Driver.sendCommandToSession (/code/node_modules/lighthouse/lighthouse-core/gather/driver.js:346:28)
      at Driver.sendCommand (/code/node_modules/lighthouse/lighthouse-core/gather/driver.js:369:17)
      at clearNetworkThrottling (/code/node_modules/lighthouse/lighthouse-core/lib/emulation.js:135:18)
      at Object.clearThrottling (/code/node_modules/lighthouse/lighthouse-core/lib/emulation.js:107:22)
      at Function.runPass (/code/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:589:21)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Function.run (/code/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:507:29)
      at async Function._gatherArtifactsFromBrowser (/code/node_modules/lighthouse/lighthouse-core/runner.js:264:23) {
    code: 'PROTOCOL_TIMEOUT',
    friendlyMessage: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Network.emulateNetworkConditions)',
    lhrRuntimeError: true,
    protocolMethod: 'Network.emulateNetworkConditions'
  }
}
[Worker] - 2023-03-03T03:03:49.426Z     INFO Early return because error found in first round.
[Worker] - 2023-03-03T03:03:49.426Z    ERROR Error occurred during job run {
  error: Error: No valid audit result for https://xxxxxxxx
      at LabJobWorker.<anonymous> (/code/packages/runner/executor/tmp/runner-scripts/job.LabAnalyze:0.0.1/lighthouse/lighthouse-worker.js:268:23)
      at Generator.throw (<anonymous>)
      at rejected (/code/node_modules/tslib/tslib.js:116:69)
      at runNextTicks (node:internal/process/task_queues:61:5)
      at listOnTimeout (node:internal/timers:528:9)
      at processTimers (node:internal/timers:502:7)
}
[Worker] - 2023-03-03T03:03:49.427Z     INFO Event emitted to server. { type: 'job.LabAnalyze' }
[Worker] - 2023-03-03T03:03:49.428Z     INFO receive shutdown message from parent

**Comment by Brooooooklyn** [comment]
Retry

**Comment by Kingwl** [comment]
> Retry

Failed again

**Comment by Kingwl** [comment]
It's *seems* only happend when Profile = IPhoneX

**Comment by xy-sea** [comment]
I also encountered this issue when I was developing locally using Docker Compose, which caused some of the Lab's runtime features to fail. The Profile was set to the default option. May I know when will this issue be fixed?

**Comment by xy-sea** [comment]
[Worker] - 2023-09-15T06:04:23.847Z    ERROR Lab Round #1 failed {
perfsee-main-job-runner-1  |   error: ProtocolError: Protocol error (Performance.enable): Target closed.
perfsee-main-job-runner-1  |       at /code/node_modules/puppeteer-core/src/common/Connection.ts:304:16
perfsee-main-job-runner-1  |       at new Promise (<anonymous>)
perfsee-main-job-runner-1  |       at CDPSession.send (/code/node_modules/puppeteer-core/src/common/Connection.ts:300:12)
perfsee-main-job-runner-1  |       at Page._initialize (/code/node_modules/puppeteer-core/src/common/Page.ts:591:20)
perfsee-main-job-runner-1  |       at Function.create (/code/node_modules/puppeteer-core/src/common/Page.ts:434:16)
perfsee-main-job-runner-1  |       at /code/node_modules/puppeteer-core/src/common/Target.ts:124:14
perfsee-main-job-runner-1  |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
perfsee-main-job-runner-1  |       at async Promise.all (index 0)
perfsee-main-job-runner-1  |       at async BrowserContext.pages (/code/node_modules/puppeteer-core/src/common/Browser.ts:764:19)
perfsee-main-job-runner-1  |       at async Promise.all (index 0) {
perfsee-main-job-runner-1  |     originalMessage: ''
perfsee-main-job-runner-1  |   }
perfsee-main-job-runner-1  | }
perfsee-main-job-runner-1  | [Worker] - 2023-09-15T06:04:23.977Z     INFO Early return because error found in first round or error occured twice.
perfsee-main-job-runner-1  | [Worker] - 2023-09-15T06:04:24.045Z    ERROR Error occurred during job run {
perfsee-main-job-runner-1  |   error: Error: No valid audit result for https://juejin.cn/
perfsee-main-job-runner-1  |       at LabJobWorker.runLighthouse (/code/packages/runner/lab/src/lighthouse/lighthouse-worker.ts:477:13)
perfsee-main-job-runner-1  |       at async LabJobWorker.audit (/code/packages/runner/lab/src/lighthouse/lighthouse-worker.ts:76:22)
perfsee-main-job-runner-1  |       at async LabJobWorker.work (/code/packages/runner/lab/src/lighthouse/index.ts:48:9)
perfsee-main-job-runner-1  |       at async LabJobWorker.run (/code/packages/runner/shared/src/worker.ts:68:7)
perfsee-main-job-runner-1  |       at async executeJob (/code/packages/runner/shared/src/index.ts:25:5)
perfsee-main-job-runner-1  | }
