### ISSUE TITLE
ERROR sendRawMessage() was called without an established connection.

### ISSUE THREAD

**Issue by xy-sea** [perfsee/perfsee#482]
I ran the project locally using yarn dev -p @perfsee/platform-server, and encountered errors when executing Lab runtime features

[Worker] - 2023-09-15T06:42:57.142Z    ERROR sendRawMessage() was called without an established connection.
[Worker] - 2023-09-15T06:42:57.142Z    ERROR sendRawMessage() was called without an established connection.
[Worker] - 2023-09-15T06:42:57.142Z    ERROR Lab Round #1 failed {
  error: Error: Cannot create new tab, and no tabs already open.
      at /Users/xxxx/code/perfsee-main/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:45:35
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Driver.connect (/Users/xxxx/code/perfsee-main/node_modules/lighthouse/lighthouse-core/gather/driver.js:119:5)
      at async Function.run (/Users/xxxx/code/perfsee-main/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:484:7)
      at async Function._gatherArtifactsFromBrowser (/Users/xxxx/code/perfsee-main/node_modules/lighthouse/lighthouse-core/runner.js:264:23)
      at async Function.gather (/Users/xxxx/code/perfsee-main/node_modules/lighthouse/lighthouse-core/runner.js:170:21)
      at async lighthouse (/Users/xxxx/code/perfsee-main/node_modules/lighthouse/lighthouse-core/index.js:50:21)
      at async LabJobWorker.runLh (/Users/xxxx/code/perfsee-main/packages/runner/lab/src/lighthouse/lighthouse-worker.ts:489:22)
      at async LabJobWorker.runLighthouse (/Users/xxxx/code/perfsee-main/packages/runner/lab/src/lighthouse/lighthouse-worker.ts:411:25)
      at async LabJobWorker.audit (/Users/xxxx/code/perfsee-main/packages/runner/lab/src/lighthouse/lighthouse-worker.ts:76:22)
}
[Worker] - 2023-09-15T06:42:57.147Z     INFO Early return because error found in first round or error occured twice.
[Worker] - 2023-09-15T06:42:57.147Z    ERROR Error occurred during job run {
error: Error: No valid audit result for https://juejin.cn/
      at LabJobWorker.runLighthouse (/Users/xxxx/code/perfsee-main/packages/runner/lab/src/lighthouse/lighthouse-worker.ts:477:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async LabJobWorker.audit (/Users/xxxx/code/perfsee-main/packages/runner/lab/src/lighthouse/lighthouse-worker.ts:76:22)
      at async LabJobWorker.work (/Users/xxxx/code/perfsee-main/packages/runner/lab/src/lighthouse/index.ts:48:9)
      at async LabJobWorker.run (/Users/xxxx/code/perfsee-main/packages/runner/shared/src/worker.ts:68:7)
      at async executeJob (/Users/xxxx/code/perfsee-main/packages/runner/shared/src/index.ts:25:5)

**Comment by EYHN** [comment]
we have https://github.com/GoogleChrome/lighthouse/issues/14930 on Chrome v111+.

https://github.com/perfsee/perfsee/pull/407
